---
#
# Playbook to launch resources on EC2
#
#

- name: Playbook to launch resources on EC2
  hosts: localhost
  connection: local
  vars_files:
    - vars/aws.yml

  pre_tasks:

    - name: Update OS packages
      yum:
        name: '*'
        state: latest
      become: true
      become_method: sudo

    - name: Install Development tools
      yum:
        name: '@Development tools'
        state: present
      become: true
      become_method: sudo

    - name: Install Python PIP
      yum:
        name: python-pip
        state: present
      become: true
      become_method: sudo

    - name: Install boto packages
      pip:
        name: '{{item}}'
        state: present
      become: true
      become_method: sudo
      with_items:
        - boto
        - botocore
        - boto3

  roles:
    - { role: ec2_operations, }

